### PR TITLE
feat(main): add 2024 apple specs

### PR DESCRIPTION
**Pull request by onderceylan**

### CODE REVIEW

**Comment by nathanchase** [comment]
Any progress on this? What's causing the failures?

**Comment by onderceylan** [comment]
It should be good now @nathanchase, do you mind giving a test?

**Comment by onderceylan** [comment]
@nathanchase this is fixed on version 6.4.0. You need to run the command on the latest version. Which version are you using? You can see it with `pwa-asset-generator --version`

**Pull request merged**
